name: Deploy Updated Code to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (required for GitHub Actions, even if we deploy via SSH)
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_RSA_KEY }}
          script: |
            cd BroncoBites
            git remote set-url origin https://eli-tolentino:${{ secrets.DEPLOY_PAT }}@github.com/YuAreMySunshine/BroncoBites.git
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            cd Backend
            npm install
            cd ../Frontend
            rm -rf dist node_modules/.vite
            npm install
            npm run build
            cd ..
            sudo pm2 restart all
            sudo pm2 save
